- hosts: all
  become: yes
  roles:
    - {role: djx339.k8s-kubeadm-install}

- hosts: master
  become: yes
  roles:
    - {role: djx339.k8s-kubeadm-master }
    - {role: djx339.k8s-kubeadm-kubectl-conf }

- hosts: nodes
  become: yes
  roles:
    - {role: djx339.k8s-kubeadm-node}
